import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import assert from 'node:assert/strict';

const installed = 'C:/Users/Admin/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
const executablePath = process.env.CHROME_PATH || (existsSync(installed) ? installed : undefined);
const browser = await chromium.launch({ executablePath, headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
const context = await browser.newContext({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 1, recordVideo: { dir: 'test-results/video', size: { width: 1600, height: 900 } } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', err => errors.push(err.message));
await mkdir('test-results', { recursive: true });
const state = () => page.evaluate(() => window.__CATAPULT__.state());
const screenshot = name => page.screenshot({ path: `test-results/${name}.png` });
try {
  await page.goto(process.env.GAME_URL || 'http://127.0.0.1:5188');
  await page.locator('#home:not([hidden])').waitFor({ timeout: 20000 });
  await page.evaluate(() => document.fonts.ready);
  await screenshot('01-home');
  await page.locator('#play').click();
  await page.waitForTimeout(600);
  await screenshot('02-ready');
  console.log('READY', JSON.stringify(await state()));
  const angle = -40 * Math.PI / 180, power = 18.7;
  const x = 232 + Math.cos(angle) * power * 29, y = 658 + Math.sin(angle) * power * 29;
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.waitForTimeout(250);
  await screenshot('03-aim');
  const aimed = await state();
  assert.ok(Math.abs(aimed.aim.angle - angle) < 0.01, `Pointer angle mismatch: ${aimed.aim.angle}`);
  assert.ok(Math.abs(aimed.aim.power - power) < 0.1, `Pointer power mismatch: ${aimed.aim.power}`);
  await page.mouse.up();
  await page.waitForFunction(() => window.__CATAPULT__.state().projectile?.x > 1010, { timeout: 6000 }, { polling: 'raf' });
  await page.keyboard.press('Space');
  await screenshot('04-impact');
  await page.locator('#result-next').waitFor({ timeout: 20000 });
  await page.waitForTimeout(550);
  await screenshot('05-result');
  console.log('RESULT', JSON.stringify(await state()));
  assert.equal((await state()).phase, 'won');
  assert.equal((await state()).stars, 3);
  await page.locator('#result-next').click();
  assert.equal((await state()).level, 1);
  await page.keyboard.press('Escape');
  const paused = await state();
  assert.equal(paused.paused, true);
  await screenshot('06-pause');
  await page.locator('#resume').click();
  await page.keyboard.press('r');
  assert.equal((await state()).shots, 0);
  await page.locator('#sound').click();
  assert.equal(await page.locator('#sound').getAttribute('aria-pressed'), 'false');
  await page.keyboard.press('Escape');
  await page.locator('#pause-levels').click();
  await screenshot('07-levels');
  assert.equal(await page.locator('#level-2').isDisabled(), true);
  await page.reload();
  await page.locator('#home:not([hidden])').waitFor();
  await page.locator('#levels').click();
  assert.equal(await page.locator('#level-1').isEnabled(), true);
  assert.equal(await page.locator('#level-0 .earned').count(), 3);
  await page.locator('#close-levels').click();
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.locator('#play').click();
  await screenshot('08-1280');
  await page.mouse.move(x * 0.8, y * 0.8);
  const resizedAim = await state();
  assert.ok(Math.abs(resizedAim.aim.angle - angle) < 0.01, `Scaled pointer angle mismatch: ${resizedAim.aim.angle}`);
  assert.ok(Math.abs(resizedAim.aim.power - power) < 0.1, `Scaled pointer power mismatch: ${resizedAim.aim.power}`);
  assert.deepEqual(errors, []);
  await writeFile('test-results/browser-report.json', JSON.stringify({ passed: true, errors, finalState: await state() }, null, 2));
  console.log('Browser smoke passed: launch, aiming, victory, stars, progression, pause, replay, mute, save, resize.');
} catch (error) {
  await screenshot('failure');
  console.error('STATE', await state().catch(() => null));
  console.error('ERRORS', errors);
  throw error;
} finally { await context.close(); await browser.close(); }
